### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by moimael** [campaignmonitor/createsend-python#21]
Hi,

It would be great to have python 3 compatibility.

Thanks !

**Comment by oscarcp** [comment]
+1 to this request. The whole python community is starting to move *at last* to python 3, and this library is part of the core of many projects out there. I think you guys should take a minute to think about it.

**Comment by duncanmcdowell** [comment]
Any movement on this? Has anyone embarked on creating a 3.3 wrapper or modifying this to accept 2.7 and 3.x?
