### ISSUE TITLE
setup.py install broken if six not installed

### ISSUE THREAD

**Issue by gregplaysguitar** [campaignmonitor/createsend-python#29]
setup.py shouldn't import the module because there's no guarantee the dependencies will be present. See my quick fix here; you may want to implement differently so the version isn't duplicated

https://github.com/gregplaysguitar/createsend-python/commit/b6961f87da9c28d4e39029a2813dc55f6fe2d662

**Comment by jdennes** [comment]
Should be fixed in https://github.com/campaignmonitor/createsend-python/releases/tag/v4.2.2.
