### ISSUE TITLE
Add lib maintainer(s) to PyPi package

### ISSUE THREAD

**Issue by SpainTrain** [campaignmonitor/createsend-python#34]
Tracking / closing the loop on @jdennes comment in https://github.com/campaignmonitor/createsend-python/issues/30#issuecomment-252610316

> I released 4.2.0 on PyPI after someone from Campaign Monitor contacted me asking about this. I'm not an active maintainer of this project, so someone from Campaign Monitor should be added as an owner of the package, since they are the maintainers of it.

**Comment by katharosada** [comment]
@jdennes I'm from CM and I would like to take over ownership of the PyPI package. Please add the 'campmon' pypi user as an owner of the package.

**Comment by jdennes** [comment]
Thank you—I've added `campmon` as an owner of the `createsend` package.
