### ISSUE TITLE
Issue installing as a dependency

### ISSUE THREAD

**Issue by power121** [campaignmonitor/createsend-python#35]
12:34:47   Downloading createsend-4.2.0.tar.gz (159kB)
12:34:47     Complete output from command python setup.py egg_info:
12:34:47     Traceback (most recent call last):
12:34:47       File "<string>", line 20, in <module>
12:34:47       File "/tmp/pip-build-RzioYi/createsend/setup.py", line 5, in <module>
12:34:47         from createsend.createsend import **version**
12:34:47       File "createsend/**init**.py", line 1, in <module>
12:34:47         ﻿from .createsend import *
12:34:47       File "createsend/createsend.py", line 6, in <module>
12:34:47         from six import BytesIO
12:34:47     ImportError: No module named six

^^ got this from one of my Jenkins jobs installing the setup.py file for a service that uses "createsend" as a dependency

**Comment by jdennes** [comment]
Should be fixed in https://github.com/campaignmonitor/createsend-python/releases/tag/v4.2.2.

**Comment by jbub** [comment]
This is still failing on 4.2.2 on pypi:

```
Collecting createsend
  Downloading createsend-4.2.2.tar.gz (160kB)
    100% |████████████████████████████████| 163kB 2.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/my/cvndjd3s70z22zmybwh59rvc0000gn/T/pip-build-EzVTCF/createsend/setup.py", line 3, in <module>
        from createsend.createsend import __version__
      File "createsend/__init__.py", line 8, in <module>
        from createsend.createsend import *
      File "createsend/createsend.py", line 12, in <module>
        from createsend.utils import VerifiedHTTPSConnection, json_to_py, get_faker
    ImportError: No module named utils
```
