### ISSUE TITLE
module on pypi is missing six dependence

### ISSUE THREAD

**Issue by veitsi** [campaignmonitor/createsend-python#39]
version of this module published on pypi is missing dependence of module six. as a result after installation of createsend module gives an error

**Comment by djstein** [comment]
@jdennes @bharling can we please merge one of these pull requests

**Comment by djstein** [comment]
create pull request #43 that should solve this problem and related issues (#29, #35)

**Comment by jdennes** [comment]
Should be fixed in https://github.com/campaignmonitor/createsend-python/releases/tag/v4.2.2.
