### ISSUE TITLE
WHATEVER CAMPAIGN MONITOR TEAM THAT OWNS THIS BURNING PILE OF RUBISH PLEASE GET YOUR ACT TOGETHER

### ISSUE THREAD

**Issue by djstein** [campaignmonitor/createsend-python#52]
**This is blunt. This is some of the worst code and worst customer service I and many others have experienced in a long time.**

**It is extremely unfortunate that your paying customers receive no support for a code base you have decided to drop with no warning. This is a Python 2 project that simply needed to be made compatible with Python 3. Many people who use this are being forced to update to Python 3 due to, well it being 2017, and other libraries dropping support for Python 2. [Even the Python Foundation is dropping support for Python 2](https://www.python.org/dev/peps/pep-0373/).**

**You could have given a intern or junior dev this as busy work. Instead no, you got a professional from another company to spend time to rewrite your library to something that resembles clean code. And now it can't even be pushed and many more of your customers are without a working environment. A number of issues now exist simply because the newest releases I MADE, not your team, needs to be deployed to PyPi. Someone has literally already done the work you were supposed to do, and you can't even spend 30 minutes to deploy the package.**

**I have reached out to your support team who informed me in ticket reference number: [ref:_00Do0eE9F._5001JRs4pf:ref](url) that someone on the "engineering team that work on the Public API" has begun looking at this. Well they certainly have dropped the ball. Still no response, still no commits to the code base from your team. Instead we have myself and @jdennes maintaining your library.**

**This is pretty frustrating, especially for the great number of engineers out there being forced to maintain connections and write work-arounds to connect to Campaign Monitor simply because we choose Python. I guess the real solution is to not choose Campaign Monitor.**

FOR ALL YOU OTHER ENGINEERS THAT HAVE TO DEAL WITH THIS, WE HAVE CREATED AN OPEN SOURCE VERSION OF THIS LIBRARY HERE: https://github.com/getbento/createsend-python

TO USE IT IN YOUR PROJECT SIMPLY ADD `git+git://github.com/getbento/createsend-python.git` TO YOUR `requirements.txt`

**Comment by katharosada** [comment]
Hi, I'm sorry for the lack of support that this library has received from CM. I'm on the case now and I'll be getting a new version of the library pushed as soon as I can.

Thank you for the work you and @jdennes have put into maintaining and updating this library, it's appreciated. We'll be doing a better job in the future.

**Comment by katharosada** [comment]
I've fixed the packaging and pushed it to version 4.2.6. Please let me know if there are any problems with this release.
