### ISSUE TITLE
Is it possible to override the From field in a smart email?

### ISSUE THREAD

**Issue by sbstp** [campaignmonitor/createsend-python#74]
I want to change the From/Reply-To fields when sending smart email. Is it possible to do this? The from field is not available in the function.

**Comment by markstaples** [comment]
Hi @sbstp - for Transactional Smart Emails, the From/Reply-To fields are defined in app for the specific email. Only Transactional Classic Emails allow for the From/Reply-To to be set on API call.

**Comment by sbstp** [comment]
Is it possible to put a template in the From field then? If I set the From field to like `[fromEmail=]` will it get replaced by the value I send in the template?

**Comment by markstaples** [comment]
Yes, you can use [FromEmail=] template variable in from field.

**Comment by sbstp** [comment]
Thanks a bunch!
